name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Rebuild list
      run: python3 compile.py
    - name: Commit changes
      run: bash commitifneeded.sh
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
