name: CI

on:
  schedule:
    - cron: 0 0/8 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: python3 compile.py
    - name: Commit changes
      uses: elstudio/actions-js-build/commit@v2-beta
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
